version: '3'
services:
  back:
    build:
      context: ./
      dockerfile: backendDockerfile
    container_name: back
    ports:
      - '3000:3000'
    restart: always
    env_file:
      - ./backend/.env
  front:
    build:
      context: ./
      dockerfile: frontendDockerfile
    container_name: front
    ports:
      - '3001:3000'
    restart: always